--1
SELECT DISTINCT S.CUSTOMER FROM SHIPPEDVSCUSTDEMAND S
WHERE S.DEMANDQTY > S.SHIPPEDQTY

--2
SELECT DISTINCT S.SUPPLIER FROM SUPPLIEDVSSHIPPED  S WHERE S.QTYORDERED > S.QTYSHIPPED

--3
SELECT DISTINCT M.MANUF FROM MATSUSEDVSSHIPPED M WHERE M.QTYORDERED > M.QTYSHIPPED

--4 (assuming what this question means is that, find the manufs who have produced the items, but not shipped them yet to the entities that require them)

SELECT DISTINCT P.MANUF FROM PRODUCEDVSSHIPPED P WHERE P.QTYPRODUCED > P.QTYSHIPPED