-------------1
CREATE VIEW shippedVsCustDemand (CUSTOMER, ITEM, DEMANDQTY, SHIPPEDQTY)
AS
SELECT CUSTOMER, ITEM, QTY, COALESCE(SHIPPEDQTY,0) AS SHIPPEDQTY
FROM
(
SELECT C.*, Q.SHIPPEDQTY
FROM 
(SELECT C.CUSTOMER, C.ITEM, C.QTY FROM CUSTOMERDEMAND C) C
LEFT OUTER JOIN
(SELECT S.ITEM, S.RECIPIENT, SUM(S.QTY) AS SHIPPEDQTY FROM SHIPORDERS S GROUP BY ITEM, RECIPIENT) Q
ON C.CUSTOMER = Q.RECIPIENT AND C.ITEM = Q.ITEM
)


-------------2
CREATE VIEW totalManufItems (ITEM, TOTALQTY)
AS
SELECT M.ITEM, SUM(M.QTY)
FROM MANUFORDERS M
GROUP BY M.ITEM

-------------3
CREATE VIEW MATSUSEDVSSHIPPED (MANUF, MATITEM, QTYORDERED, QTYSHIPPED)
AS
SELECT MANUF, MATITEM, QTYORDERED, COALESCE(QTYSHIPPED,0) AS QTYSHIPPED FROM
(
SELECT O.MANUF, O.MATITEM, O.QTYORDERED, S.QTY AS QTYSHIPPED
FROM
  (
  SELECT C.MANUF, C.MATITEM, SUM(C.QTY*C.QTYMATPERITEM) AS QTYORDERED
  FROM
  (SELECT M.MANUF, B.PRODITEM, M.QTY, B.MATITEM, B.QTYMATPERITEM FROM MANUFORDERS M, BILLOFMATERIALS B WHERE M.ITEM = B.PRODITEM) C
  GROUP BY C.MANUF, C.MATITEM
  ) O
  LEFT OUTER JOIN
  SHIPORDERS S
ON S.ITEM = O.MATITEM AND S.RECIPIENT = O.MANUF
)

-------------4
CREATE VIEW PRODUCEDVSSHIPPED (ITEM, MANUF, QTYPRODUCED, QTYSHIPPED)
AS
SELECT ITEM, MANUF, QTY AS QTYPRODUCED, COALESCE(QTYSHIPPED,0) AS QTYSHIPPED
FROM
(
SELECT C.*, Q.QTYSHIPPED
FROM 
(SELECT * FROM MANUFORDERS) C
LEFT OUTER JOIN
(SELECT S.ITEM, S.SENDER, SUM(S.QTY) AS QTYSHIPPED FROM SHIPORDERS S GROUP BY ITEM, SENDER) Q
ON C.MANUF = Q.SENDER AND C.ITEM = Q.ITEM
)

------------5
CREATE VIEW SUPPLIEDVSSHIPPED (ITEM, SUPPLIER, QTYORDERED, QTYSHIPPED)
AS
SELECT ITEM, SUPPLIER, QTY AS QTYORDERED, COALESCE(QTYSHIPPED,0) AS QTYSHIPPED
FROM
(
SELECT U.*, Q.QTYSHIPPED
FROM 
(SELECT * FROM SUPPLYORDERS) U
LEFT OUTER JOIN
(SELECT S.ITEM, S.SENDER, SUM(S.QTY) AS QTYSHIPPED FROM SHIPORDERS S GROUP BY ITEM, SENDER) Q
ON U.SUPPLIER = Q.SENDER AND U.ITEM = Q.ITEM
)

----------------6
CREATE VIEW PERSUPPLIERCOST (SUPPLIER, ITEM, COST)
AS
SELECT Z.SUPPLIER, SUM(Z.AMTAFTERDISC)
FROM
(
(SELECT SUPPLIER, AMT AS AMTAFTERDISC
FROM
  (
    SELECT * FROM
    ((SELECT S.SUPPLIER, S.ITEM, (S.QTY*U.PPU) AS AMT
    FROM SUPPLYORDERS S, SUPPLYUNITPRICING U 
    WHERE S.SUPPLIER = U.SUPPLIER AND S.ITEM = U.ITEM) Z
    JOIN
    SUPPLIERDISCOUNTS D
    USING(SUPPLIER)
    )
  )
WHERE AMT < AMT1
)
UNION
(SELECT SUPPLIER, (AMT-DISC1*AMT) AS AMTAFTERDISC
FROM
  (
    SELECT * FROM
    ((SELECT S.SUPPLIER, S.ITEM, (S.QTY*U.PPU) AS AMT
    FROM SUPPLYORDERS S, SUPPLYUNITPRICING U 
    WHERE S.SUPPLIER = U.SUPPLIER AND S.ITEM = U.ITEM) Z
    JOIN
    SUPPLIERDISCOUNTS D
    USING(SUPPLIER)
    )
  )
WHERE AMT>=AMT1 AND AMT<AMT2
)
UNION
(SELECT SUPPLIER, (AMT-DISC2*AMT) AS AMTAFTERDISC
FROM
  (
    SELECT * FROM
    ((SELECT S.SUPPLIER, S.ITEM, (S.QTY*U.PPU) AS AMT
    FROM SUPPLYORDERS S, SUPPLYUNITPRICING U 
    WHERE S.SUPPLIER = U.SUPPLIER AND S.ITEM = U.ITEM) Z
    JOIN
    SUPPLIERDISCOUNTS D
    USING(SUPPLIER)
    )
  )
WHERE AMT>=AMT2
)
) Z
GROUP BY Z.SUPPLIER

-----------7
CREATE VIEW PERMANUFCOST (MANUF, COST)
AS
SELECT Z.MANUF, SUM(Z.AMTAFTERDISC)
FROM
(
(SELECT MANUF, AMT AS AMTAFTERDISC
FROM
  (
    SELECT * FROM
    ((SELECT M.MANUF, M.ITEM, (M.QTY*U.PRODCOSTPERUNIT + U.SETUPCOST) AS AMT
    FROM MANUFORDERS M, MANUFUNITPRICING U 
    WHERE M.MANUF = U.MANUF AND M.ITEM = U.PRODITEM) Z
    JOIN
    MANUFDISCOUNTS D
    USING(MANUF)
    )
  )
WHERE AMT < AMT1
)
UNION
(SELECT MANUF, (AMT-DISC1*AMT) AS AMTAFTERDISC
FROM
  (
    SELECT * FROM
    ((SELECT M.MANUF, M.ITEM, (M.QTY*U.PRODCOSTPERUNIT + U.SETUPCOST) AS AMT 
    FROM MANUFORDERS M, MANUFUNITPRICING U 
    WHERE M.MANUF = U.MANUF AND M.ITEM = U.PRODITEM) Z
    JOIN
    MANUFDISCOUNTS D
    USING(MANUF)
    )
  )
WHERE AMT>=AMT1
)
) Z
GROUP BY Z.MANUF

---------------8 (assuming what this question means is that, for the current shipping orders in SHIPORDERS, find how much each shipper is charging, considering the weight and quantity of the items, and the locations of senders and recipients)

SELECT X.SHIPPER, SUM(X.TOTALPRICE) FROM
(
(SELECT R.SHIPPER, (R.PRICEPERLB*Z.ITEMWEIGHT) AS TOTALPRICE, R.FROMLOC, R.TOLOC
FROM
SHIPPINGPRICING R,
(SELECT DISTINCT I.SHIPPER, SUM(I.ITEMWEIGHT) AS ITEMWEIGHT, B.SENDLOC, B.RECLOC 
FROM
  (SELECT S.ITEM, S.SHIPPER, (I.UNITWEIGHT*S.QTY) AS ITEMWEIGHT FROM SHIPORDERS S, ITEMS I WHERE S.ITEM = I.ITEM) I,
  (SELECT S.ITEM, S.SHIPPER, B.SHIPLOC AS SENDLOC, B1.SHIPLOC AS RECLOC 
  FROM SHIPORDERS S, BUSENTITIES B, BUSENTITIES B1 WHERE S.SENDER = B.ENTITY AND S.RECIPIENT = B1.ENTITY AND B.ENTITY != B1.ENTITY) B
WHERE I.ITEM = B.ITEM AND I.SHIPPER = B.SHIPPER
GROUP BY(I.SHIPPER, B.SENDLOC, B.RECLOC)
) Z
WHERE
R.SHIPPER = Z.SHIPPER AND R.FROMLOC = Z.SENDLOC AND R.TOLOC = Z.RECLOC AND (R.PRICEPERLB*Z.ITEMWEIGHT) < R.AMT1
)
UNION
(SELECT R.SHIPPER, (R.PRICEPERLB*Z.ITEMWEIGHT - R.DISC1*R.PRICEPERLB*Z.ITEMWEIGHT) AS TOTALPRICE, R.FROMLOC, R.TOLOC
FROM
SHIPPINGPRICING R,
(SELECT DISTINCT I.SHIPPER, SUM(I.ITEMWEIGHT) AS ITEMWEIGHT, B.SENDLOC, B.RECLOC 
FROM
  (SELECT S.ITEM, S.SHIPPER, (I.UNITWEIGHT*S.QTY) AS ITEMWEIGHT FROM SHIPORDERS S, ITEMS I WHERE S.ITEM = I.ITEM) I,
  (SELECT S.ITEM, S.SHIPPER, B.SHIPLOC AS SENDLOC, B1.SHIPLOC AS RECLOC 
  FROM SHIPORDERS S, BUSENTITIES B, BUSENTITIES B1 WHERE S.SENDER = B.ENTITY AND S.RECIPIENT = B1.ENTITY AND B.ENTITY != B1.ENTITY) B
WHERE I.ITEM = B.ITEM AND I.SHIPPER = B.SHIPPER
GROUP BY(I.SHIPPER, B.SENDLOC, B.RECLOC)
) Z
WHERE
R.SHIPPER = Z.SHIPPER AND R.FROMLOC = Z.SENDLOC AND R.TOLOC = Z.RECLOC AND (R.PRICEPERLB*Z.ITEMWEIGHT) >= R.AMT1 AND (R.PRICEPERLB*Z.ITEMWEIGHT) < R.AMT2
)
UNION
(
SELECT R.SHIPPER, (R.PRICEPERLB*Z.ITEMWEIGHT - R.DISC2*R.PRICEPERLB*Z.ITEMWEIGHT) AS TOTALPRICE, R.FROMLOC, R.TOLOC
FROM
SHIPPINGPRICING R,
(SELECT DISTINCT I.SHIPPER, SUM(I.ITEMWEIGHT) AS ITEMWEIGHT, B.SENDLOC, B.RECLOC 
FROM
  (SELECT S.ITEM, S.SHIPPER, (I.UNITWEIGHT*S.QTY) AS ITEMWEIGHT FROM SHIPORDERS S, ITEMS I WHERE S.ITEM = I.ITEM) I,
  (SELECT S.ITEM, S.SHIPPER, B.SHIPLOC AS SENDLOC, B1.SHIPLOC AS RECLOC 
  FROM SHIPORDERS S, BUSENTITIES B, BUSENTITIES B1 WHERE S.SENDER = B.ENTITY AND S.RECIPIENT = B1.ENTITY AND B.ENTITY != B1.ENTITY) B
WHERE I.ITEM = B.ITEM AND I.SHIPPER = B.SHIPPER
GROUP BY(I.SHIPPER, B.SENDLOC, B.RECLOC)
) Z
WHERE
R.SHIPPER = Z.SHIPPER AND R.FROMLOC = Z.SENDLOC AND R.TOLOC = Z.RECLOC AND (R.PRICEPERLB*Z.ITEMWEIGHT) >= R.AMT2
)
) X
GROUP BY (X.SHIPPER)


-----------9
SELECT * FROM
(SELECT SUM(P.PRICE) AS TOTALSUPPLYCOST FROM
(
(SELECT S.ITEM, S.SUPPLIER, (S.QTY* U.PPU) AS PRICE FROM SUPPLYORDERS S, SUPPLYUNITPRICING U, SUPPLIERDISCOUNTS D
WHERE S.ITEM = U.ITEM AND S.SUPPLIER = U.SUPPLIER AND S.SUPPLIER = D.SUPPLIER AND (S.QTY* U.PPU) < D.AMT1)
UNION
(SELECT S.ITEM, S.SUPPLIER, (S.QTY* U.PPU - D.DISC1*S.QTY* U.PPU) AS PRICE FROM SUPPLYORDERS S, SUPPLYUNITPRICING U, SUPPLIERDISCOUNTS D
WHERE S.ITEM = U.ITEM AND S.SUPPLIER = U.SUPPLIER AND S.SUPPLIER = D.SUPPLIER AND (S.QTY* U.PPU) >= D.AMT1 AND (S.QTY* U.PPU) < D.AMT2)
UNION
(SELECT S.ITEM, S.SUPPLIER, (S.QTY* U.PPU - D.DISC2*S.QTY* U.PPU) AS PRICE FROM SUPPLYORDERS S, SUPPLYUNITPRICING U, SUPPLIERDISCOUNTS D
WHERE S.ITEM = U.ITEM AND S.SUPPLIER = U.SUPPLIER AND S.SUPPLIER = D.SUPPLIER AND (S.QTY* U.PPU) >= D.AMT1 AND (S.QTY* U.PPU) >= D.AMT2)
) P
),

(
SELECT SUM(P.PRICE) AS TOTALMANUFCOST FROM
(
(SELECT M.ITEM, M.MANUF, (M.QTY*U.PRODCOSTPERUNIT + U.SETUPCOST) AS PRICE FROM MANUFORDERS M, MANUFUNITPRICING U, MANUFDISCOUNTS D
WHERE M.ITEM = U.PRODITEM AND M.MANUF = U.MANUF AND M.MANUF = D.MANUF AND (M.QTY*U.PRODCOSTPERUNIT + U.SETUPCOST) < D.AMT1)
UNION
(SELECT M.ITEM, M.MANUF, (M.QTY*U.PRODCOSTPERUNIT + U.SETUPCOST) AS PRICE FROM MANUFORDERS M, MANUFUNITPRICING U, MANUFDISCOUNTS D
WHERE M.ITEM = U.PRODITEM AND M.MANUF = U.MANUF AND M.MANUF = D.MANUF AND (M.QTY*U.PRODCOSTPERUNIT + U.SETUPCOST) >= D.AMT1)
) P
),

(
SELECT SUM(X.TOTALPRICE) AS TOTALSHIPPINGCOST FROM
(
(SELECT R.SHIPPER, (R.PRICEPERLB*Z.ITEMWEIGHT) AS TOTALPRICE, R.FROMLOC, R.TOLOC
FROM
SHIPPINGPRICING R,
(SELECT DISTINCT I.SHIPPER, SUM(I.ITEMWEIGHT) AS ITEMWEIGHT, B.SENDLOC, B.RECLOC 
FROM
  (SELECT S.ITEM, S.SHIPPER, (I.UNITWEIGHT*S.QTY) AS ITEMWEIGHT FROM SHIPORDERS S, ITEMS I WHERE S.ITEM = I.ITEM) I,
  (SELECT S.ITEM, S.SHIPPER, B.SHIPLOC AS SENDLOC, B1.SHIPLOC AS RECLOC 
  FROM SHIPORDERS S, BUSENTITIES B, BUSENTITIES B1 WHERE S.SENDER = B.ENTITY AND S.RECIPIENT = B1.ENTITY AND B.ENTITY != B1.ENTITY) B
WHERE I.ITEM = B.ITEM AND I.SHIPPER = B.SHIPPER
GROUP BY(I.SHIPPER, B.SENDLOC, B.RECLOC)
) Z
WHERE
R.SHIPPER = Z.SHIPPER AND R.FROMLOC = Z.SENDLOC AND R.TOLOC = Z.RECLOC AND (R.PRICEPERLB*Z.ITEMWEIGHT) < R.AMT1
)
UNION
(SELECT R.SHIPPER, (R.PRICEPERLB*Z.ITEMWEIGHT - R.DISC1*R.PRICEPERLB*Z.ITEMWEIGHT) AS TOTALPRICE, R.FROMLOC, R.TOLOC
FROM
SHIPPINGPRICING R,
(SELECT DISTINCT I.SHIPPER, SUM(I.ITEMWEIGHT) AS ITEMWEIGHT, B.SENDLOC, B.RECLOC 
FROM
  (SELECT S.ITEM, S.SHIPPER, (I.UNITWEIGHT*S.QTY) AS ITEMWEIGHT FROM SHIPORDERS S, ITEMS I WHERE S.ITEM = I.ITEM) I,
  (SELECT S.ITEM, S.SHIPPER, B.SHIPLOC AS SENDLOC, B1.SHIPLOC AS RECLOC 
  FROM SHIPORDERS S, BUSENTITIES B, BUSENTITIES B1 WHERE S.SENDER = B.ENTITY AND S.RECIPIENT = B1.ENTITY AND B.ENTITY != B1.ENTITY) B
WHERE I.ITEM = B.ITEM AND I.SHIPPER = B.SHIPPER
GROUP BY(I.SHIPPER, B.SENDLOC, B.RECLOC)
) Z
WHERE
R.SHIPPER = Z.SHIPPER AND R.FROMLOC = Z.SENDLOC AND R.TOLOC = Z.RECLOC AND (R.PRICEPERLB*Z.ITEMWEIGHT) >= R.AMT1 AND (R.PRICEPERLB*Z.ITEMWEIGHT) < R.AMT2
)
UNION
(
SELECT R.SHIPPER, (R.PRICEPERLB*Z.ITEMWEIGHT - R.DISC2*R.PRICEPERLB*Z.ITEMWEIGHT) AS TOTALPRICE, R.FROMLOC, R.TOLOC
FROM
SHIPPINGPRICING R,
(SELECT DISTINCT I.SHIPPER, SUM(I.ITEMWEIGHT) AS ITEMWEIGHT, B.SENDLOC, B.RECLOC 
FROM
  (SELECT S.ITEM, S.SHIPPER, (I.UNITWEIGHT*S.QTY) AS ITEMWEIGHT FROM SHIPORDERS S, ITEMS I WHERE S.ITEM = I.ITEM) I,
  (SELECT S.ITEM, S.SHIPPER, B.SHIPLOC AS SENDLOC, B1.SHIPLOC AS RECLOC 
  FROM SHIPORDERS S, BUSENTITIES B, BUSENTITIES B1 WHERE S.SENDER = B.ENTITY AND S.RECIPIENT = B1.ENTITY AND B.ENTITY != B1.ENTITY) B
WHERE I.ITEM = B.ITEM AND I.SHIPPER = B.SHIPPER
GROUP BY(I.SHIPPER, B.SENDLOC, B.RECLOC)
) Z
WHERE
R.SHIPPER = Z.SHIPPER AND R.FROMLOC = Z.SENDLOC AND R.TOLOC = Z.RECLOC AND (R.PRICEPERLB*Z.ITEMWEIGHT) >= R.AMT2
)
) X
)